# This is the attack of Wang et al. "Beyond Inferring Class Representatives: User-Level
# Privacy Leakage From Federated Learning"
# However currently still without the multitask-GAN employed therein for refinement

defaults:
  - _default_optimization_attack
  - _self_
type: beyond-infering

optim:
  optimizer: L-BFGS
  step_size: 1.0
  boxed: True
  max_iterations: 400

regularization:
  total_variation:
    scale: 0.2352 # This is 0.00015 from the original work multiplied by 28^2*2 (the number of MNIST pixels and filters)
    inner_exp: 2
    outer_exp: 1.25
